[package]
name = "rustforged2"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = [
    "dynamic_linking",
    "jpeg",
    "webp",
    "bmp",
    "tiff",
    "gif",
] }
bevy_egui = "0.38"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.15"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Improve runtime performance by limiting trace logging levels at compile time.
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
