# cargo-packager configuration
# https://github.com/crabnebula-dev/cargo-packager

name = "rustforged"
product-name = "Rustforged"
version = "0.1.0"
identifier = "com.fitz11.rustforged"
description = "D&D 5E Virtual Tabletop Map Editor"
authors = ["fitz11"]
license-file = "LICENSE-MIT"
homepage = "https://github.com/fitz11/rustforged"
out-dir = "target/release/packager"
binaries-dir = "target/release"
icons = ["packaging/icons/icon.ico", "packaging/icons/icon.icns"]
resources = [{ src = "assets", target = "assets" }]

[[binaries]]
path = "rustforged"
main = true

[macos]
minimum-system-version = "11.0"
